[context.production.environment]
  JEKYLL_ENV = "production"
  NODE_ENV = "production"

[context.branch-deploy.environment]
  JEKYLL_ENV = "staging"
  NODE_ENV = "production"

[context.deploy-preview.environment]
  JEKYLL_ENV = "staging"
  NODE_ENV = "production"
