name: Netlify Deploy
on:
  schedule:
  - cron: "0 15 * * *"

jobs:
  build:
    name: Build site
    runs-on: ubuntu-latest
    steps:
    - name: Call netlify build url
      run: curl -X POST ${{ secrets.NETLIFY_BUILD_URL }}
      
    
